version: 2.1

executors:
  node:
    docker:
      - image: cimg/node

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
  integration_test:
    executor: node
    steps:
      - run: |
          echo localhost.example.com 127.0.0.1 >> /etc/hosts
      - run: npm test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - integration_test:
          requires:
            - build
