version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:15.0.1
jobs:
  # build:
  #   executor: node
  #   steps:
  #     - checkout
  #     - run: npm ci
  #     - run: npm run build
  integration_test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: |
          echo 127.0.0.1 localhost.example.com | sudo tee -a /etc/hosts
          echo 127.0.0.1 collect.example.org | sudo tee -a /etc/hosts
      - run: npm test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      # - build
      - integration_test
          # requires:
          #   - build
