version: 2.1
executors:
  node:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:15.3
jobs:
  automation_test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          - npm-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Configure DNS
          command: |
            echo 127.0.0.1 test-website.example | sudo tee -a /etc/hosts
            echo 127.0.0.1 test-report-cookies.example | sudo tee -a /etc/hosts
            echo 127.0.0.1 test-third-party.example | sudo tee -a /etc/hosts
      - run:
          name: Run automation tests
          command: npm test
  build:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: ~/workspace
          paths: .
  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/workspace/.npmrc
      - run:
          name: Sync version with git
          command: npm --no-git-tag-version version $CIRCLE_TAG
      - run:
          name: Publish package
          command: npm publish


workflows:
  version: 2
  ci:
    jobs:
      - automation_test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - automation_test
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
